# There is support for influxdb v3 (core) OSS, but it's highly recommended to use Influxdb 1.x versions with this project. 

apiVersion: v1
kind: Secret
metadata:
  name: garmin-grafana-secret
type: Opaque
stringData:
  INFLUXDB_USERNAME: influxdb_user
  INFLUXDB_PASSWORD: influxdb_secret_password
  #####################################################################################
  # GARMINCONNECT_EMAIL: your_garminconnect_email # optional, read the setup docs. (remove or comment out this line altogether if not used)
  # GARMINCONNECT_BASE64_PASSWORD: your_base64_encoded_garminconnect_password # optional, must be Base64 encoded, read setup docs. (remove or comment out this line altogether if not used)
  #####################################################################################
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fetch-data-config
data:
  INFLUXDB_HOST: influxdb
  INFLUXDB_PORT: "8086" # Influxdb V3 maps to 8181 instead of 8086 of V1
  INFLUXDB_DATABASE: GarminStats
  GARMINCONNECT_IS_CN: "False"  # Set this to True if you are in mainland China or use Garmin-cn (Default False)
  # The following ENV variables are required only if you are using influxdb V3 (You won't have to set the above )
  #######################################################################################
  #  INFLUXDB_VERSION: "1" # Required for influxdb V3, Default is 1, must be overridden with 3 if using Influxdb V3
  #  INFLUXDB_V3_ACCESS_TOKEN: your_influxdb_admin_access_token # Required for influxdb V3 (ignored for V1), Set this to your admin access token
  ########################################################################################
  # The following ENV variables will override some default settings.
  # Please read the README guide before using them as they may change how the script behaves
  ########################################################################################
  # LOG_LEVEL: INFO # change to DEBUG to get DEBUG logs
  # UPDATE_INTERVAL_SECONDS: "300" # Default update check interval is set to 5 minutes
  # FETCH_SELECTION: daily_avg,sleep,steps,heartrate,stress,breathing,hrv,vo2,activity,race_prediction,body_composition # This enables selection of fetch data : Check Discussion #119 to know what additional options are available (add them seperated by , but without a space)
  # KEEP_FIT_FILES: "False" # Stores the FIT files (downloads and saves them) when set to True - read docs for more details
  # ALWAYS_PROCESS_FIT_FILES: "False" # Enables processing FIT files even if GPS data is not present in it when set to True, default False
  # USER_TIMEZONE: "" # Can hardcode user's timezone - must be a valid TZ identifier like Europe/Budapest without quotes, fetches timezone automatically and dynamically on each run if set to empty (default) - Read docs
  # INFLUXDB_ENDPOINT_IS_HTTP: "True" # Set this to False if you are using HTTPS for your influxdb connection (over the internet)
  # FORCE_REPROCESS_ACTIVITIES: "True" # Enables re-processing of FIT files on iterative updates when set to True (default), setting to False may save processing time but known for skipping activities
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
data:
  INFLUXDB_DB: GarminStats
  INFLUXDB_DATA_INDEX_VERSION: tsi1
  ###############################################################
  # The following ENV variables are applicable for InfluxDB V3
  ###############################################################
  # INFLUXDB3_MAX_HTTP_REQUEST_SIZE: "10485760"
  # INFLUXDB3_NODE_IDENTIFIER_PREFIX: Influxdb-node1
  # INFLUXDB3_BUCKET: GarminStats
  # INFLUXDB3_OBJECT_STORE: file
  # INFLUXDB3_DB_DIR: /data
  # INFLUXDB3_QUERY_FILE_LIMIT: "5000" # this set to be a very high value if you want to view long term data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garmin-token-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb
          image: influxdb:1.11
          envFrom:
            - configMapRef:
                name: influxdb-config
          env:
            - name: INFLUXDB_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: garmin-grafana-secret
                  key: INFLUXDB_PASSWORD
            - name: INFLUXDB_USER
              valueFrom:
                secretKeyRef:
                  name: garmin-grafana-secret
                  key: INFLUXDB_USERNAME
          ports:
            - containerPort: 8086
          volumeMounts:
            - name: influxdb-storage
              mountPath: /var/lib/influxdb
      volumes:
        - name: influxdb-storage
          persistentVolumeClaim:
            claimName: influxdb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  selector:
    app: influxdb
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: garmin-fetch-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: garmin-fetch-data
  template:
    metadata:
      labels:
        app: garmin-fetch-data
    spec:
      securityContext:
        fsGroup: 65532
      containers:
        - name: garmin-fetch-data
          image: ghcr.io/zewelor/garmin-grafana:latest
          securityContext:
            runAsUser: 65532
            runAsGroup: 65532
            runAsNonRoot: true
          envFrom:
            - configMapRef:
                name: fetch-data-config
            - secretRef:
                name: garmin-grafana-secret
          volumeMounts:
            - name: garmin-token
              mountPath: /home/nonroot/.garminconnect
      volumes:
        - name: garmin-token
          persistentVolumeClaim:
            claimName: garmin-token-pvc
---
######################################################################################################
# Remove all below if you already have a Grafana instance running and don't need to set up a new one #
######################################################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  GF_SECURITY_ADMIN_USER: "admin"
  GF_SECURITY_ADMIN_PASSWORD: "admin"
  GF_PLUGINS_PREINSTALL: "marcusolsson-hourly-heatmap-panel"
  GF_DATE_FORMATS_FULL_DATE: "MMM Do, YYYY - hh:mm:ss a"
  GF_DATE_FORMATS_INTERVAL_SECOND: "hh:mm:ss a"
  GF_DATE_FORMATS_INTERVAL_MINUTE: "hh:mm a"
  GF_DATE_FORMATS_INTERVAL_HOUR: "MMM DD hh:mm a"
  GF_DATE_FORMATS_INTERVAL_DAY: "MMM DD"
  GF_DATE_FORMATS_INTERVAL_MONTH: "YYYY-MM"
  GF_DATE_FORMATS_INTERVAL_YEAR: "YYYY"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          envFrom:
            - configMapRef:
                name: grafana-config
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana
      volumes:
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-data
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31007
  type: NodePort
