grafana:
  enabled: true
  envFromSecret: "{{ .Release.Name }}-credentials"
  rbac:
    create: false
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts:
      - &grafana_host yourhost.example.com
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-staging"
      external-dns.alpha.kubernetes.io/ttl: "120"
      external-dns.alpha.kubernetes.io/hostname: *grafana_host
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    tls:
      - secretName: yourhost-tls
        hosts:
          - *grafana_host
  plugins:
    - marcusolsson-hourly-heatmap-panel
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - uid: DS_GARMIN_STATS
          name: GarminInflux
          type: influxdb
          url: "http://{{ .Release.Name }}-influxdb:8086"
          database: GarminStats
          user: $__env{INFLUXDB_USERNAME}
          secureJsonData:
            password: $__env{INFLUXDB_PASSWORD}
  dashboards:
    garmin:
      garmin-dashboard:
        gnetId: 23245
        revision: 2
        datasource:
          - name: DS_GARMIN_STATS
            value: GarminInflux
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: garmin
          folder: Garmin
          type: file
          options:
            path: /var/lib/grafana/dashboards/garmin

influxdb:
  image:
    repository: influxdb
    tag: "1.11"
  persistence:
    enabled: false 
    #size: 5Gi
    #storageClass: ""
  auth:
    database: GarminStats
    username: admin
    password: password
    adminUser: admin
    adminPassword: password
  env:
    - name: INFLUXDB_DB
      value: "{{ .Values.influxdb.auth.database }}"
    - name: INFLUXDB_HTTP_AUTH_ENABLED
      value: "true"
garmin:
  image:
    repository: ghcr.io/zewelor/garmin-grafana
    tag: latest
  port: 8000
  credentials:
    email: example@example.com
    base64Password: password
  tokens:
    persistence:
      enabled: false
      #size: 100Mi
      #storageClass: ""
  env:
    - name: INFLUXDB_HOST
      value: "{{ .Release.Name }}-influxdb"
    - name: INFLUXDB_PORT
      value: "8086"
    - name: INFLUXDB_DATABASE
      value: "{{ .Values.influxdb.auth.database }}"
    - name: INFLUXDB_ENDPOINT_IS_HTTP
      value: "True"
    - name: INFLUXDB_VERSION
      value: "1"
    - name: ALWAYS_PROCESS_FIT_FILES
      value: "True"
    - name: FETCH_INTERVAL
      value: "15min"
    # - name: MANUAL_START_DATE # will cause batch mode / restarts
    #   value: "2025-06-06"
