{
 "title": "Garmin Stats",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Intraday Health Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Heart Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"HeartRate\") AS \"Heart Rate\" FROM \"HeartRateIntraday\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 2m FILL(NULL)"
    }
   ]
  },
  {
   "title": "Last Sync ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT now() AS \"time\", last(\"HeartRate\") AS \"HeartRate\" FROM \"HeartRateIntraday\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp)"
    }
   ]
  },
  {
   "title": "Heart Rate Distribution",
   "type": "histogram",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", mean_value FROM (SELECT timestamp, avg(\"HeartRate\") AS mean_value FROM \"HeartRateIntraday\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1m FILL(NULL)) WHERE mean_value <= 96"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", mean_value FROM (SELECT timestamp, avg(\"HeartRate\") AS mean_value FROM \"HeartRateIntraday\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1m FILL(NULL)) WHERE mean_value > 96"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", mean_value FROM (SELECT timestamp, avg(\"HeartRate\") AS mean_value FROM \"HeartRateIntraday\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1m FILL(NULL)) WHERE mean_value < 60"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", mean_value FROM (SELECT timestamp, avg(\"HeartRate\") AS mean_value FROM \"HeartRateIntraday\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1m FILL(NULL)) WHERE mean_value > 110"
    }
   ]
  },
  {
   "title": "Stress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", \"stressLevel\" AS \"Stress\" FROM \"StressIntraday\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) ORDER BY timestamp"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", \"BodyBatteryLevel\" AS \"Body Battery\" FROM \"BodyBatteryIntraday\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Today RHR",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", last(\"restingHeartRate\") AS \"restingHeartRate\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    }
   ]
  },
  {
   "title": "Today's Steps",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", last(\"totalSteps\") AS \"totalSteps\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    }
   ]
  },
  {
   "title": "Steps Cumulative (24h)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"StepsCount\") AS \"Intraday Steps\" FROM \"StepsIntraday\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 15m FILL(NULL)"
    }
   ]
  },
  {
   "title": "Today SpO2",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", cast(NULL as double) AS \"averageSpo2\" FROM \"DailyStats\" WHERE 1=0"
    }
   ]
  },
  {
   "title": "Steps Hourly (24h)",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 21, "x": 3, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", sum(\"StepsCount\") AS \"Hourly Steps\" FROM \"StepsIntraday\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1h FILL(0)"
    }
   ]
  },
  {
   "title": "Last Sleep Hours",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", last(\"sleepTimeSeconds\") AS \"Total Asleep\" FROM \"SleepSummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    }
   ]
  },
  {
   "title": "Breathing Rates",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"BreathingRate\") AS \"BR\" FROM \"BreathingRateIntraday\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 2m FILL(NULL)"
    }
   ]
  },
  {
   "title": "High Stress Duration",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", last(\"highStressDuration\") AS \"Stress\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    }
   ]
  },
  {
   "title": "Sleep Movement Activity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", \"SleepMovementActivityLevel\" AS \"Sleeping Movement Activity\" FROM \"SleepIntraday\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Last Sleep",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", last(\"deepSleepSeconds\") AS \"Deep\" FROM \"SleepSummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", last(\"lightSleepSeconds\") AS \"Light\" FROM \"SleepSummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", last(\"remSleepSeconds\") AS \"REM\" FROM \"SleepSummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", last(\"awakeSleepSeconds\") AS \"Awake\" FROM \"SleepSummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    }
   ]
  },
  {
   "title": "Sleep Intraday Stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", \"heartRate\" AS \"Sleeping Heart Rate\" FROM \"SleepIntraday\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) ORDER BY timestamp"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", cast(NULL as double) AS \"SpO2\" FROM \"SleepIntraday\" WHERE 1=0"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", \"hrvValue\" AS \"HRV\" FROM \"HRV_Intraday\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Today Activity",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", last(\"sedentarySeconds\") AS \"Sedentary\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", (last(\"vigorousIntensityMinutes\") * 60) AS \"Intense Activity\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", (last(\"moderateIntensityMinutes\") * 60) AS \"Moderate Activity\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", last(\"sleepingSeconds\") AS \"Sleeping\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    }
   ]
  },
  {
   "title": "Sleep Stages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 52 },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", \"SleepStageLevel\" + 1 AS \"SleepStageLevel\" FROM \"SleepIntraday\" WHERE \"SleepStageLevel\"=0 AND timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) ORDER BY timestamp"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", \"SleepStageLevel\" + 1 AS \"SleepStageLevel\" FROM \"SleepIntraday\" WHERE \"SleepStageLevel\"=1 AND timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) ORDER BY timestamp"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", \"SleepStageLevel\" + 1 AS \"SleepStageLevel\" FROM \"SleepIntraday\" WHERE \"SleepStageLevel\"=2 AND timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) ORDER BY timestamp"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", \"SleepStageLevel\" + 1 AS \"SleepStageLevel\" FROM \"SleepIntraday\" WHERE \"SleepStageLevel\"=3 AND timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Activity HR Zones (mean)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"hrTimeInZone_1\") AS \"Zone 1\" FROM \"ActivitySummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"hrTimeInZone_2\") AS \"Zone 2\" FROM \"ActivitySummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"hrTimeInZone_3\") AS \"Zone 3\" FROM \"ActivitySummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"hrTimeInZone_4\") AS \"Zone 4\" FROM \"ActivitySummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"hrTimeInZone_5\") AS \"Zone 5\" FROM \"ActivitySummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    }
   ]
  },
  {
   "title": "Activity Calories (mean)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", \"calories\" AS \"calories\" FROM \"ActivitySummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) ORDER BY timestamp"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", \"bmrCalories\" AS \"BMR calories\" FROM \"ActivitySummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Activity HR difference (Max-Avg)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 4, "x": 10, "y": 59 },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"averageHR\") AS \"avgHR\" FROM \"ActivitySummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY $__interval FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"maxHR\") AS \"maxHR\" FROM \"ActivitySummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY $__interval FILL(NULL)"
    }
   ]
  },
  {
   "title": "Activity Distance",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", \"distance\" AS \"Distance\" FROM \"ActivitySummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Activity Duration",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", \"elapsedDuration\" AS \"Duration\" FROM \"ActivitySummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) ORDER BY timestamp"
    }
   ]
  },
  { "title": "Recent Activities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Recent Activity",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", \"activityType\" AS \"Activity Type\" FROM \"ActivitySummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) AND \"activityType\" != 'No Activity' ORDER BY timestamp"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", \"elapsedDuration\" AS \"Duration\" FROM \"ActivitySummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) AND \"activityType\" != 'No Activity' ORDER BY timestamp"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", \"maxHR\" AS \"Max HR\" FROM \"ActivitySummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) AND \"activityType\" != 'No Activity' ORDER BY timestamp"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", (\"maxSpeed\" * 3.6) AS \"Max Speed\" FROM \"ActivitySummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) AND \"activityType\" != 'No Activity' ORDER BY timestamp"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", \"distance\" AS \"Distance\" FROM \"ActivitySummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) AND \"activityType\" != 'No Activity' ORDER BY timestamp"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", \"activityName\" AS \"Location\" FROM \"ActivitySummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) AND \"activityType\" != 'No Activity' ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Activities",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", \"activityType\" AS \"Activity Timeline\" FROM \"ActivitySummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) UNION ALL SELECT now() AS \"time\", 'No Activity' AS \"Activity Timeline\" FROM (SELECT count() AS c FROM \"ActivitySummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp)) WHERE c = 0 ORDER BY 1"
    }
   ]
  },
  { "title": "Long term visualization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Week at a Glance",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", max(\"totalDistanceMeters\") AS \"Distance Covered\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", max(\"totalSteps\") AS \"Steps\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", max(\"sleepingSeconds\") AS \"Total Sleep\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", max(\"highStressDuration\") AS \"High Stress Duration\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", max(\"highlyActiveSeconds\") AS \"High Activity Duration\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", max(\"restingHeartRate\") AS \"Resting Heart Rate\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", cast(NULL as double) AS \"Avg SpO2\" FROM \"DailyStats\" WHERE 1=0"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", max(\"bodyBatteryChargedValue\") AS \"Body Battery Change\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    }
   ]
  },
  {
   "title": "Daily Steps",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"totalSteps\") AS \"Steps\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    }
   ]
  },
  {
   "title": "Daily Distance",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", max(\"totalDistanceMeters\") AS \"Distance Covered\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    }
   ]
  },
  {
   "title": "Daily Calories",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"bmrKilocalories\") AS \"BMR Calories\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"activeKilocalories\") AS \"Activity Calories\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    }
   ]
  },
  {
   "title": "Daily avg health metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", cast(NULL as double) AS \"Avg SpO2\" FROM \"SleepSummary\" WHERE 1=0"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"hrvValue\") AS \"Avg HRV\" FROM \"HRV_Intraday\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"restingHeartRate\") AS \"Avg Resting HR\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    }
   ]
  },
  {
   "title": "Daily avg health metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"BreathingRate\") AS \"Avg Breathing Rate\" FROM \"BreathingRateIntraday\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"stressLevel\") AS \"Avg Stress\" FROM \"StressIntraday\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"avgSleepStress\") AS \"Avg Sleeping Stress\" FROM \"SleepSummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    }
   ]
  },
  {
   "title": "Race Predictions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"time5K\") AS \"Time 5K\" FROM \"RacePredictions\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"time10K\") AS \"Time 10K\" FROM \"RacePredictions\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"timeHalfMarathon\") AS \"Half Marathon\" FROM \"RacePredictions\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"timeMarathon\") AS \"Full Marathon\" FROM \"RacePredictions\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    }
   ]
  },
  {
   "title": "VO2 Max",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"VO2_max_value\") AS \"VO2 Max\" FROM \"VO2_Max\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    }
   ]
  },
  {
   "title": "Sleep Stages",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"deepSleepSeconds\") AS \"Deep Sleep\" FROM \"SleepSummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 12h FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"lightSleepSeconds\") AS \"Light Sleep\" FROM \"SleepSummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 12h FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"remSleepSeconds\") AS \"REM Sleep\" FROM \"SleepSummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 12h FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"awakeSleepSeconds\") AS \"Awake\" FROM \"SleepSummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 12h FILL(NULL)"
    }
   ]
  },
  {
   "title": "Avg Activity over given duration",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 7, "x": 9, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"sedentarySeconds\") AS \"Sedentary\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"highlyActiveSeconds\") AS \"Intense Activity\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"activeSeconds\") AS \"Fair Activity\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"sleepingSeconds\") AS \"Sleeping\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    }
   ]
  },
  {
   "title": "Sleep Score",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"sleepScore\") AS \"Sleep Score\" FROM \"SleepSummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    }
   ]
  },
  {
   "title": "Daily Activity Overview",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"sleepingSeconds\") AS \"Sleeping\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"sedentarySeconds\") AS \"Sedentary\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"activeSeconds\") AS \"Active\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"highlyActiveSeconds\") AS \"Highly Active\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    }
   ]
  },
  {
   "title": "Body Battery overview",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 8, "x": 9, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"bodyBatteryChargedValue\") AS \"Charged\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", (avg(\"bodyBatteryDrainedValue\") * -1) AS \"Drained\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    }
   ]
  },
  {
   "title": "Daily Intensity Minutes",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", (max(\"moderateIntensityMinutes\") * 60) AS \"Moderate Intensity\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", (max(\"vigorousIntensityMinutes\") * 60) AS \"Vigorous Intensity\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    }
   ]
  },
  {
   "title": "Stress overview",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"lowStressDuration\") AS \"Low Stress duration\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"restStressDuration\") AS \"Rest stress duration\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"mediumStressDuration\") AS \"Medium stress duration\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"uncategorizedStressDuration\") AS \"Uncategorized stress duration\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"highStressDuration\") AS \"High stress duration\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    }
   ]
  },
  {
   "title": "Average Sleep trends",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"deepSleepSeconds\") AS \"Deep\" FROM \"SleepSummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"lightSleepSeconds\") AS \"Light\" FROM \"SleepSummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"remSleepSeconds\") AS \"REM\" FROM \"SleepSummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"awakeSleepSeconds\") AS \"Awake\" FROM \"SleepSummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    }
   ]
  },
  {
   "title": "Body Battery Level Change",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 143 },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"bodyBatteryLowestValue\") AS \"bb_low\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"bodyBatteryHighestValue\") AS \"bb_high\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    }
   ]
  },
  {
   "title": "Weight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"weight\") AS \"Weight in KG\" FROM \"BodyComposition\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY $__interval FILL(NULL)"
    }
   ]
  },
  {
   "title": "HR Range (Max-Min)",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 150 },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"minHeartRate\") AS \"hr_low\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"maxHeartRate\") AS \"hr_high\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    }
   ]
  },
  {
   "title": "Month at a Glance (Daily Average)",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 157 },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"restingHeartRate\") AS \"Resting HR\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"highStressDuration\") AS \"High Stress Duration\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"activeSeconds\") AS \"Active time\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"bodyBatteryHighestValue\") AS \"Body Battery (Highest)\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"totalSteps\") AS \"Total Steps\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", cast(NULL as double) AS \"SpO2\" FROM \"DailyStats\" WHERE 1=0"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"sleepScore\") AS \"Sleep Score\" FROM \"SleepSummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"sleepingSeconds\") AS \"Total Sleep\" FROM \"DailyStats\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"hrvValue\") AS \"HRV\" FROM \"HRV_Intraday\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1d FILL(NULL)"
    }
   ]
  },
  {
   "title": "Month at a Glance (Intraday)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 168 },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", count(\"HeartRate\") AS \"Band Wearing\" FROM \"HeartRateIntraday\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 2m FILL(0)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", approx_percentile(\"HeartRate\", 0.5) AS \"HR Zones\" FROM \"HeartRateIntraday\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1h FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", approx_percentile(\"BodyBatteryLevel\", 0.5) AS \"Body Battery\" FROM \"BodyBatteryIntraday\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1h FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", approx_percentile(\"stressLevel\", 0.5) AS \"Stress Level\" FROM \"StressIntraday\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1h FILL(NULL)"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", sum(\"StepsCount\") AS \"Steps Taken\" FROM \"StepsIntraday\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1h FILL(NULL)"
    }
   ]
  },
  {
   "title": "HR Histogram Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 176 },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", avg(\"HeartRate\") AS \"Heart Rate\" FROM \"HeartRateIntraday\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY $__interval FILL(NULL)"
    }
   ]
  },
  {
   "title": "Hourly walk heatmap",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"Time\", avg(\"StepsCount\") AS \"Value\" FROM \"StepsIntraday\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY $__interval FILL(NULL)"
    }
   ]
  },
  {
   "title": "Sleep Regularity",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 184 },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"Time\", avg(\"SleepStageLevel\") AS \"Value\" FROM \"SleepIntraday\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) SAMPLE BY 1h FILL(NULL)"
    }
   ]
  },
  {
   "title": "Support Me!",
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": {
    "content": "<center><a href='https://ko-fi.com/A0A84F3DP' target='_blank'><img height='36' style='border:0px;height:36px;' src='https://storage.ko-fi.com/cdn/kofi2.png?v=6' border='0' alt='Buy Me a Coffee at ko-fi.com' /></a></center>  "
   }
  }
 ]
}