{
 "title": "Garmin GPS",
 "tags": [ "gps" ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "ActivityGPS",
    "label": "Activity with GPS",
    "query": "SELECT DISTINCT \"ActivitySelector\" AS __text, \"ActivitySelector\" AS __value FROM \"ActivitySummary\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) ORDER BY 1 DESC"
   }
  ]
 },
 "panels": [
  {
   "title": "GPS Track by Velocity",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", \"Latitude\" AS \"lat\" FROM \"ActivityGPS\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) AND \"ActivitySelector\" = '$ActivityGPS' ORDER BY timestamp"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", \"Longitude\" AS \"lon\" FROM \"ActivityGPS\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) AND \"ActivitySelector\" = '$ActivityGPS' ORDER BY timestamp"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", \"HeartRate\" AS \"HR\" FROM \"ActivityGPS\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) AND \"ActivitySelector\" = '$ActivityGPS' ORDER BY timestamp"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", (\"Speed\" * 3.6) AS \"speed (Km/h)\" FROM \"ActivityGPS\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) AND \"ActivitySelector\" = '$ActivityGPS' ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "GPS Track by Heart Rate",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", \"Latitude\" AS \"lat\" FROM \"ActivityGPS\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) AND \"ActivitySelector\" = '$ActivityGPS' ORDER BY timestamp"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", \"Longitude\" AS \"lon\" FROM \"ActivityGPS\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) AND \"ActivitySelector\" = '$ActivityGPS' ORDER BY timestamp"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", \"HeartRate\" AS \"HR\" FROM \"ActivityGPS\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) AND \"ActivitySelector\" = '$ActivityGPS' ORDER BY timestamp"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", \"Speed\" AS \"speed\" FROM \"ActivityGPS\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) AND \"ActivitySelector\" = '$ActivityGPS' ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "GPS Track Heart Rate",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", \"HeartRate\" AS \"HR\" FROM \"ActivityGPS\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) AND \"ActivitySelector\" = '$ActivityGPS' ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "GPS Track Cadence",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", (\"Cadence\" * 2) AS \"Cadence\" FROM \"ActivityGPS\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) AND \"ActivitySelector\" = '$ActivityGPS' ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Distance vs HR",
   "type": "trend",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", \"Distance\" AS \"Distance\" FROM \"ActivityGPS\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) AND \"ActivitySelector\" = '$ActivityGPS' ORDER BY timestamp"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", \"HeartRate\" AS \"Heart Rate\" FROM \"ActivityGPS\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) AND \"ActivitySelector\" = '$ActivityGPS' ORDER BY timestamp"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", (\"Speed\" * 3.6) AS \"Pace\" FROM \"ActivityGPS\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) AND \"ActivitySelector\" = '$ActivityGPS' ORDER BY timestamp"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", \"DurationSeconds\" AS \"Duration\" FROM \"ActivityGPS\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) AND \"ActivitySelector\" = '$ActivityGPS' ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Heart Rate vs Pace",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", (\"Speed\" * 3.6) AS \"Speed (Km/h)\" FROM \"ActivityGPS\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) AND \"ActivitySelector\" = '$ActivityGPS' ORDER BY timestamp"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", \"HeartRate\" AS \"Heart Rate\" FROM \"ActivityGPS\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) AND \"ActivitySelector\" = '$ActivityGPS' ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "GPS Track pace",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", \"Speed\" AS \"m/s\" FROM \"ActivityGPS\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) AND \"ActivitySelector\" = '$ActivityGPS' ORDER BY timestamp"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", \"DurationSeconds\" AS \"Duration\" FROM \"ActivityGPS\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) AND \"ActivitySelector\" = '$ActivityGPS' ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "GPS Track Altitude",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", \"Altitude\" AS \"Altitude\" FROM \"ActivityGPS\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) AND \"ActivitySelector\" = '$ActivityGPS' ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Heatmap for GPS Activity (within selected time)",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 100 },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", \"Latitude\" AS \"lat\" FROM \"ActivityGPS\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) ORDER BY timestamp"
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", \"Longitude\" AS \"lon\" FROM \"ActivityGPS\" WHERE timestamp BETWEEN cast(${__from}*1000 as timestamp) AND cast(${__to}*1000 as timestamp) ORDER BY timestamp"
    }
   ]
  }
 ]
}